from __future__ import annotations

import ast
import math
import re
import shutil
import subprocess
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path

_GENERATED_MARKERS = (
    "generated file",
    "do not edit",
    "automatically generated",
    "@generated",
    "code generated by",
)


@dataclass(slots=True)
class QualityReport:
    accepted: bool
    score: float
    syntax_valid: bool
    generated: bool
    minified: bool
    meaningful_identifiers: bool
    reasons: list[str]

    def to_dict(self) -> dict:
        return asdict(self)


def score_code(content: str, language: str, *, min_score: float = 0.70) -> QualityReport:
    reasons: list[str] = []
    stripped = content.strip()
    if len(stripped) < 50:
        return QualityReport(False, 0.0, False, False, False, False, ["too_short"])

    generated = any(marker in stripped[:1500].lower() for marker in _GENERATED_MARKERS)
    if generated:
        reasons.append("generated_marker")
    lines = stripped.splitlines()
    average_line = sum(len(line) for line in lines) / max(1, len(lines))
    very_long = sum(1 for line in lines if len(line) > 300)
    minified = average_line > 180 or very_long / max(1, len(lines)) > 0.20
    if minified:
        reasons.append("minified_or_bundled")

    syntax_valid = _syntax_valid(stripped, language)
    if not syntax_valid:
        reasons.append("syntax_invalid")

    identifiers = re.findall(r"\b[A-Za-z_][A-Za-z0-9_]{2,}\b", stripped)
    meaningful_identifiers = len(set(identifiers)) >= 3
    if not meaningful_identifiers:
        reasons.append("weak_identifiers")

    comment_lines = sum(1 for line in lines if line.lstrip().startswith(("#", "//", "/*", "*")))
    comment_ratio = comment_lines / max(1, len(lines))
    structure = min(1.0, math.log2(max(2, len(lines))) / 8)
    score = (
        0.40 * float(syntax_valid)
        + 0.20 * float(meaningful_identifiers)
        + 0.20 * structure
        + 0.10 * float(0.01 <= comment_ratio <= 0.50)
        + 0.10 * float(not minified and not generated)
    )
    accepted = score >= min_score and syntax_valid and not generated and not minified
    return QualityReport(
        accepted,
        round(score, 4),
        syntax_valid,
        generated,
        minified,
        meaningful_identifiers,
        reasons,
    )


def _syntax_valid(content: str, language: str) -> bool:
    language = language.lower()
    if language == "python":
        try:
            ast.parse(content)
            return True
        except SyntaxError:
            return False
    try:
        from tree_sitter_language_pack import get_parser

        parser = get_parser(
            {"javascript": "javascript", "typescript": "typescript", "cpp": "cpp"}.get(
                language, language
            )
        )
        tree = parser.parse(content.encode("utf-8"))
        return not tree.root_node.has_error
    except Exception:
        return _compiler_parse(content, language)


def _compiler_parse(content: str, language: str) -> bool:
    commands = {
        "javascript": (["node", "--check", "{file}"], ".js"),
        "typescript": (["tsc", "--noEmit", "--pretty", "false", "{file}"], ".ts"),
        "go": (["gofmt", "-e", "{file}"], ".go"),
        "rust": (["rustc", "--crate-type", "lib", "{file}", "-o", "{out}"], ".rs"),
        "java": (["javac", "{file}"], ".java"),
        "cpp": (["g++", "-fsyntax-only", "{file}"], ".cpp"),
        "c++": (["g++", "-fsyntax-only", "{file}"], ".cpp"),
    }
    item = commands.get(language)
    if item is None or shutil.which(item[0][0]) is None:
        # Unknown is not accepted as valid by the final gate.
        return False
    template, suffix = item
    with tempfile.TemporaryDirectory(prefix="nova-parse-") as tmp:
        file = Path(tmp) / f"source{suffix}"
        file.write_text(content, encoding="utf-8")
        command = [part.format(file=str(file), out=str(Path(tmp) / "out")) for part in template]
        proc = subprocess.run(
            command, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=15, check=False
        )
        return proc.returncode == 0
